// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
}
export {}
